name: build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: yarn
      run: yarn
    - name: build
      run: |-
        docker build --platform linux/amd64 . -t davidsiaw/nicedoc
    - name: dockerlogin
      uses: docker/login-action@v3
      with:
        username: davidsiaw
        password: ${{ secrets.DOCKER_PAT }}
    - name: push branch
      if: github.ref != 'refs/heads/master'
      run: |-
        TAG=`git rev-parse --abbrev-ref HEAD`
        docker push davidsiaw/nicedoc:$TAG
    - name: push master
      if: github.ref == 'refs/heads/master'
      run: |-
        TAG=`date +%Y%m%d%H%M%S`
        docker tag davidsiaw/nicedoc:latest davidsiaw/nicedoc:$TAG

        docker push davidsiaw/nicedoc:latest
        docker push davidsiaw/nicedoc:$TAG
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: push master
      run: |-
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "874280+davidsiaw@users.noreply.github.com"
        sh deploy.sh

'on':
  push:
    branches:
    - '*'
